### ISSUE TITLE
 Test-DSCConfiguration -ReferenceConfiguration not working

### ISSUE THREAD

**Issue by rajukiranlr** [microsoft/Microsoft365DSC#1121]
Thanks for the above link, now am able to extract the Exchange configuration Data, **now next step is to  just monitor for any changes in the configuration and find the Event for the same,** 
if you have any documents to for same please share it. 

**current configuration -** 
Authentication using App ID and Certificate
Wordload = EXO 

Test-DSCConfiguration -ReferenceConfiguration "C:\Users\rajukiranlr\Desktop\MBG\newfolder\M365TenantConfig\localhost.mof" -ComputerName localhost
WARNING: [RAJMBGVM01]:                            [[EXOAntiPhishPolicy]f246151c-d03c-42dd-817e-8c01626a9859] The names
of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include unapproved verbs that
 might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
with the Verbose parameter. For a list of approved verbs, type Get-Verb.
**PowerShell DSC resource MSFT_EXOAntiPhishPolicy  failed to execute Test-TargetResource functionality with error
message: You must specify either the GlobalAdminAccount or ApplicationId, TenantId and CertificateThumbprint**
parameters.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

_Originally posted by @rajukiranlr in https://github.com/microsoft/Microsoft365DSC/issues/1099#issuecomment-801196141_

**Comment by rajukiranlr** [comment]
can anyone help here, i am getting error stating provide the Authentication details, not sure how to pass the Authentication details (ApplicationId, TenantId and CertificateThumbprint)

**Comment by desmay** [comment]
Are you using latest version of Microsoft365DSC there were fixed some issue with EXO due to latest EXO PowerShell module? Once the export is complete you should see configurationdata.psd1 file. If you plan to apply these config setting to another tenant simply replace the values with new values from target tenant otherwise if monitoring changes in source tenant simply compile the mof file. 

Once the mof file is complied you can run Test-DSCConfiguration M365TenantConfig -verbose
