### ISSUE TITLE
Updating the Core Microsoft365DSC module - Dev install fails

### ISSUE THREAD

**Issue by nlangsto** [microsoft/Microsoft365DSC#1218]
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

Install-M365DSCDevBranch

#### The operating system the target node is running

Machine was recently reset with full clean win10

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB, en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev

![image](https://user-images.githubusercontent.com/34170392/118840984-c814c200-b8bf-11eb-8aac-4aae5e9df57e.png)

Updating the Core Microsoft365DSC module...Remove-Module : Cannot bind argument to parameter 'Name' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.21.512.1\modules\M365DSCUtil.psm1:1496 char:19
+     Remove-Module $oldModule -Force | Out-Null
+                   ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Module], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveModul
   eCommand

Done

**Comment by stvnmbr1** [comment]
Had this yesterday, closing the powershell and execute in a new window worked for me.

**Comment by nlangsto** [comment]
Yeah, sadly I tried last week, and again this morning, new elevated windows, all the same unfortunately.

**Comment by beerhoff** [comment]
Clean installation. Have same issue. Closing the Powershell window doesn't help. Please advise.

PS C:\WINDOWS\system32> Install-M365DSCDevBranch                                                                        WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include    unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Downloading the Zip package...Done
Installing {AzureADPreview}...Done
Installing {DSCParser}...Done
Installing {ExchangeOnlineManagement}...Done
Installing {Microsoft.Graph.Authentication}...Done
Installing {Microsoft.Graph.Groups.Planner}...Done
Installing {Microsoft.Graph.Intune}...Done
Installing {Microsoft.Graph.Planner}...Done
Installing {Microsoft.Graph.Teams}...Done
Installing {Microsoft.PowerApps.Administration.PowerShell}...WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Done
Installing {MicrosoftTeams}...Done
Installing {MSCloudLoginAssistant}...Done
Installing {PnP.PowerShell}...Done
Installing {ReverseDSC}...Done
Updating the Core Microsoft365DSC module...Remove-Module : Cannot bind argument to parameter 'Name' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:1508 char:19
+     Remove-Module $oldModule -Force | Out-Null
+                   ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-Module], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveModul
   eCommand

Done
PS C:\WINDOWS\system32>

**Comment by beerhoff** [comment]
> Clean installation. Have same issue. Closing the Powershell window doesn't help. Please advise.
> 
> PS C:\WINDOWS\system32> Install-M365DSCDevBranch WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
> Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
> Downloading the Zip package...Done
> Installing {AzureADPreview}...Done
> Installing {DSCParser}...Done
> Installing {ExchangeOnlineManagement}...Done
> Installing {Microsoft.Graph.Authentication}...Done
> Installing {Microsoft.Graph.Groups.Planner}...Done
> Installing {Microsoft.Graph.Intune}...Done
> Installing {Microsoft.Graph.Planner}...Done
> Installing {Microsoft.Graph.Teams}...Done
> Installing {Microsoft.PowerApps.Administration.PowerShell}...WARNING: The names of some imported commands from the module 'Microsoft.PowerApps.Administration.PowerShell' include
> unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
> Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
> Done
> Installing {MicrosoftTeams}...Done
> Installing {MSCloudLoginAssistant}...Done
> Installing {PnP.PowerShell}...Done
> Installing {ReverseDSC}...Done
> Updating the Core Microsoft365DSC module...Remove-Module : Cannot bind argument to parameter 'Name' because it is null.
> At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\modules\M365DSCUtil.psm1:1508 char:19
> 
> * ```
>   Remove-Module $oldModule -Force | Out-Null
>   ```
> * ```
>                 ~~~~~~~~~~
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   
>   * CategoryInfo          : InvalidData: (:) [Remove-Module], ParameterBindingValidationException
>   * FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.RemoveModul
>     eCommand
> 
> Done
> PS C:\WINDOWS\system32>

Finally it works after multiple reboots and reinstalls with closing the Powershell windows after each step

**Comment by NikCharlebois** [comment]
Glad to hear
