### ISSUE TITLE
Generate Report from Config just hangs

### ISSUE THREAD

**Issue by jcegielsk1** [microsoft/Microsoft365DSC#1234]
Using version 1.21.519.2 and the previous version, running the following:
Export-M365DSCConfiguration -Quiet -GlobalAdminAccount $creds -Workloads @("TEAMS") -FileName "TeamsSettings.ps1" -ConfigurationName TeamsSettings -GenerateInfo $true                successfully creates the config file and the psd file.  However, when I run the command to export to a report,
New-M365DSCReportFromConfiguration -Type HTML -ConfigurationPath .\TeamsSettings.ps1 -OutputPath .\GorrieTeamsSettings.html -Verbose       it just hangs and my CPU spikes and never recovers.  No report file is ever created.

Also, tried to just run the GUI, and select all Teams components, same thing happens.  I also noticed no .mof file is ever created when trying to run the .ps1 file.  Is this even needed anymore?

Thanks,  Jon

**Comment by Swampen** [comment]
Have you checked the content in the `TeamsSettings.ps1` file?
I managed to replicate the problem you are facing when the configuration is empty (like below)
```powershell
    Node localhost
    {
    }
```

**Comment by Cryzor** [comment]
We had the same issue but found the root cause. 

Check your ConfigurationFile. In our case, the file was created with a previous version of Microsoft365DSC and updated it in the meantime. 

Means, in our file there was the following command:
Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.21.317.1'

But we had installed an update to version 1.21.609.2
With this, version 1.21.317.1 is no longer available and the report cannot be done. 

Simple edit the line in the configuration file to the version installed on your machine and run the command again.

**Comment by NikCharlebois** [comment]
Yes, you need to make sure that the versions mentioned in the .ps1 files you are comparing is installed on the machine where you are doing the delta report from otherwise it won't be able to parse it properly.
