### ISSUE TITLE
SPODocumentLibrary: Create Document Library & Add "Everyone except external users" to site visitors group

### ISSUE THREAD

**Issue by stvnmbr1** [microsoft/Microsoft365DSC#1324]
### Description
As of now, if an OrgAssetLibrary is deployed with SPOOrgAssetLibrary:

- and document library is not created yet, deployment fails
- and document library exists, but in a different site, deployment fails

I created my own scripts but i think this would benefit the Microsoft365DSC module in the long run.

### Proposed properties
Add new resource :  SPODocumentLibrary

- Allows creation / deletion / edit of document libraries
- Allows adding / deleting "Everyone except external users" to site visitors group

- if document library is not created yet, create document library
- if document library exists, but in a different site, break deployment and return the current document library location of the OrgAssetLibraries

### Special considerations or limitations
none that i can think of, right now

**Comment by NikCharlebois** [comment]
We try to avoid playing in the Data plane. The challenge with these types of resources is that users are allowed to modify them by design and that will throw drifts left and right. Imagine defining an SPODocumentLibrary object that defines a list of columns (e.g. Title, Category, Associated Project Code, etc.) Users that have permissions can go an rename a column, that the beauty of SPO. But doing so will create a drift and if the LCM is set to ApplyAndAutocorrect, DSC will undo the column renaming behind the users' back, creating a lot of confusion. SPOSite is also in that grey zone where it has a foot in both the Data and Control planes. The planner resources are clearly in the Data plane, but these were submitted to M365DSC as part of a migration project.

If someone writes the SPODocumentLibrary resource, we will happily include it. It is not however something the Core M365DSC team will spend time on. Maybe a better option is to let the SPOOrgAssetLibrary create the library if it doesn't exist?

**Comment by stvnmbr1** [comment]
I was considering both options, let the SPOOrgAssetLibrary create the library if it doesn't exist and an extra resource for Document Libraries.

Didn't use exporting/LCM, yet, so I did not think about that. I understand that for SPO not all components/setting should not be included as dsc, as this will result in conflict with the endusers actions.

I'll start with editing the SPOOrgAssetLibrary to create library if non existing and set in the same site as other Org Asset Libraries. If not in the same site, throw error with path of current Org Asset Libraries.

I'll think if I would like to have SPODocumentLibrary. I'll close this issue for now, i can reopen when i would like to go further with this resource.

Thanks for the explanation and considering the proposal!
