### ISSUE TITLE
Installing errror- 

### ISSUE THREAD

**Issue by Perrinw** [microsoft/Microsoft365DSC#1406]
#### Details of the scenario you tried and the problem that is occurring

Installing error
S C:\WINDOWS\system32> Install-Module Microsoft365DSC -Force -AllowClobber
PackageManagement\Install-Package : Unable to find dependent module(s) (MicrosoftTeams)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MicrosoftTeams:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

#### Verbose logs showing the problem
n/a
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```
Install-Module Microsoft365DSC -Force -AllowClobber

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)

Installing fresh on 9/2/21 10pm central time

**Comment by BChaloupka** [comment]
@Perrinw I'm getting the same error on two separate machines using PowerShell 5.0.1 and PowerShell 7. I tried different things since yesterday, but nothing works. Looks like an error in the package installation script.
I tried to user -Verbose parameter and this is the line where it hangs:

**VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='MicrosoftTeams'' for ''.**
PackageManagement\Install-Package : Unable to find dependent module(s) (MicrosoftTeams)
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MicrosoftTeams:String) [Install-Package], Exception
    + FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

The only difference in the error messages is the line and character in the PSModule.psm1 and it depends on what version of PowerShellGet module you use. I used 1.0.0.1 and 2.2.5. In both case the error appears.

**Comment by BChaloupka** [comment]
@Perrinw Just had connected discussion in different issue. Please see this: https://github.com/microsoft/Microsoft365DSC/issues/1405#issuecomment-912496927
It should help. For me it works.

**Comment by Perrinw** [comment]
@BChaloupka Thank you so much that worked for me!
