### ISSUE TITLE
New-M365DSCDeltaReport issues when using as an application 

### ISSUE THREAD

**Issue by seiken27** [microsoft/Microsoft365DSC#1548]
Hey everyone

I have started moving from using credentials to application auth via certificate, I transcripted an export and comparison where it uses App Auth, the comparison fails and reports on all resources failing.

Exports work fine, it's just the delta comparison fails. Exports are done using the same version of the module as well.

PS>TerminatingError(Compare-Object): "Cannot bind argument to parameter 'ReferenceObject' because it is null."
Error "ResourceName"

This does not happen and works fine with Teams/SecComp since User Credential is required there, but for AAD/EXO/SPO/Intune it fails.

Anyone know what could be wrong? Any assistance would be great.

**Comment by saturninlepoulet** [comment]
Hello,

That seems similar to #1541

**Comment by saturninlepoulet** [comment]
Hello,

I was about to submit an issue for this. I got same issue. Comparing an export (with credential) to another (with certificate) fails because some paramaters are not present

I used module 1.21.1103.1 and patched it by adding in M365DSCReport.psm1 this line :

```powershell
if ($propertyName -match '^(NonNodeData|ApplicationId|CertificateThumbprint|TenantId)$') { continue }
```

right after 
```powershell 
foreach ($propertyName in $sourceResource.Keys)```

and after 
```powershell
foreach ($propertyName in $destinationResource.Keys)
```

in Compare-M365DSCConfigurations function
