### ISSUE TITLE
OneDrive support for AppSecret

### ISSUE THREAD

**Issue by anpiskai** [microsoft/Microsoft365DSC#1581]
With the change to use Microsoft Graph, working with SPO resources with username/password appears to no longer use the PNP application to get and apply changes and now uses the Microsoft Graph application directly. 

In order to avoid the use of the Microsoft Graph module to provide least-privilege and avoid app sprawl, it would be nice to be able to transition OneDrive to use a custom app registration with an App Secret as a bridge until a certificate can be obtained.

**Comment by desmay** [comment]
This error is coming from our authentication module. We use the Get-MgDomain in order to derive admin url from user name and password. You must grant Graph PowerShell permission in your tenant. You can run the following:  Connect-MgGraph -Scopes "Domain.Read.All". 
https://docs.microsoft.com/en-us/graph/powershell/get-started#sign-in
