### ISSUE TITLE
Technical issue: DevOps installed module error

### ISSUE THREAD

**Issue by BurgerhoutJ** [microsoft/Microsoft365DSC#1760]
Hi,

I have set up a devops pipeline and when I want to run a job, I receive an error.

I installed the Microsoft365DSC module manual and I did the Update-M365DSCDependencies command. So on the server, I have version 1.22.209.1 installed and DevOps didn't liked this, because DevOps wants 1.21.825.1. 
See the screenshot below for more info.

![image](https://user-images.githubusercontent.com/25769575/154068682-e9f7bce7-bd3d-4122-ba4b-2f1cac7dddc7.png)

Please advice me what to do.
The local VM is a Server 2019 btw.

**Comment by andikrueger** [comment]
Could you share the build script of your pipeline? Somehow I get the feeling, there is an `install-module microsoft365dsc` used without a required version or the configuration has an explicit `Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.21.825.1'`.

**Comment by ykuijs** [comment]
This is caused by an update in the module and this not being reflected in the whitepaper yet.

Recently we changed the module not to automatically install the sub modules when installing M365DSC. The most recent version of the whitepaper was created before that, so doesn't take this scenario into account.

Please add the `Update-M365DSCDependencies` cmdlet to the build.ps1 and deploy.ps1 files to make sure all dependencies are installed as well.

I will make sure this is updated in the next version of the whitepaper.

**Comment by ykuijs** [comment]
I was wrong here, it is a little different:
v1.21.825.1 required v2.5.0 of the MicrosoftTeams module, but that version was pulled from the PowerShell Gallery. That is causing this issue.

Please update the version to be used by the scripts in `DscResources.psd1` to 1.22.209.1 and also add the `Update-M365DSCDependencies` to the build.ps1 and deploy.ps1 scripts. That should fix the issue!
