### ISSUE TITLE
MFA for Configuration (Forward)

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#180]
I am going to need all the brain power we can get on this one. The ReverseDSC approach within Office365DSC works great. Users get prompted at the beginning of the extraction, and then the Refresh Token is passed between the various workloads. The forward path however, still does not handle MFA as it should (Start-DSCConfiguration).

When a user is prompted for MFA login, there need to be a GUI popup that then generates the MFA prompt on the users' devices. When running Start-DSCConfiguration, there are no ways to display such a GUI popup during the execution. If the .mof file was compiled with an MFA Enforced account, then the user will get the following error:

_Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application._

Based on how the LCM engine for DSC is built, I don't believe we will be able to change this behavior and go around it. However, I believe there might be a way to get that prompt in at compilation time, and then pass the authentication token at runtime from within the .mof.

Three potential options that would need to be investigated:

1 - Write a new resource, name it O365Authentication, that would simply take in the GlobalAdminAccount for the MFA enabled account. Upon compilation, this would prompt the MFA GUI, and somehow get the authentication token and store it within the mof. Feasibility for this would have to be investigated further.

2 - Modify resources to take in a new "RefreshToken" parameter, that would represent the Refresh Token for the workload. In this scenario, a user would have to run an authentication script before hand, which would prompt the MFA GUI, then grab the RefreshToken, and pass it into the configuration at compilation time, most likely using a property in the ConfigurationData. This would be less straightforward for users that are new to DSC, but may end up being our only solution.

3 - Use a Script resource that would spin off a new PoSh interactive session, prompt for MFA, bring this token back into the main configuration process and use it throughout. This is the ideal scenario, but we would need to investigate further how Script resources are being handled.

**Comment by poiriersimon** [comment]
@NikCharlebois one of the issue is than ADAL is not giving us access to the refresh token anymore (since V3). The only token we have access to is the Access Token which is valid for 1h.
The refresh token is store in the session, is hidden and only accessible by ADAL itself. 

One way would be to leverage ADAL V2, but it is old and whatever is old in the cloud is usually unsecured and could be deprecated at some point. V2 is giving us the Refresh Token directly and we need to store and leverage it manually. 

One (partial) solution would be to create an Azure AD App, this could work for AAD, SPO, PnP, MSOL and Teams, but EXO and SCC would be a problem due to the internal way they are doing the RBAC which can't be granted to an AzureAD App.
