### ISSUE TITLE
All reports are now blank - both New report from config and Delta reports

### ISSUE THREAD

**Issue by gitmanphilly** [microsoft/Microsoft365DSC#1878]
#### Details of the scenario you tried and the problem that is occurring
When printing a new report from config it comes back empty/blank, no info in excel.  When getting delta report from two configs it comes back as 'no discrepancy' when known discrepancies exist.
#### Verbose logs showing the problem
No logs to show the issue but I will check - neither tasks fails with an error
#### Suggested solution to the issue
The data from the ps1 files is not being pulled into either report
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by berg95** [comment]
You are experiencing this on dev?

**Comment by grabery** [comment]
Having the same problem, using version 1.22.406.1
Empty reports :-(

**Comment by IntuneAdmin** [comment]
Have the same issue

**Comment by andikrueger** [comment]
Could you try to run the reports with the latest version?

**Comment by IntuneAdmin** [comment]
> Could you try to run the reports with the latest version?

I did it with the new version

But only get an html file of 1KB with emplate Details
![MS365DSC](https://user-images.githubusercontent.com/93092915/163555737-4662e5ec-5890-4bac-b2ea-b1b0d583f50f.png)


`New-M365DSCReportFromConfiguration -Type 'HTML' -ConfigurationPath 'D:\Microsoft365\Exchange\M365TenantConfig.ps1' -OutputPath 'D:\Microsoft365\Exchange\M365Report.html'`

**Comment by pl-kyle** [comment]
Same.  Previous version was showing the resourceID value different on all workloads as well.  
![image](https://user-images.githubusercontent.com/104104141/164324684-59939fdf-e41f-4a87-973f-60d9dcd80c9a.png)

**Comment by krugerd** [comment]
I reported same issue with New-M365DSCReportFromConfiguration (see #1845)  This now works for me in 1.22.420.1

**Comment by AbdelmounaimZaidi** [comment]
I'm working with the version 1.22.420.1 but the reports are still showing blank.

**Comment by jprotop** [comment]
Hi All, 

I have the most recent build of the Microsoft365DSC (see below) but always on a new configuration export, I'm getting a new ResourceID for the resources that are being selected for export, as a result comparing reports doesn't be helpful at all since all resources considered changed.

Any idea how this can be fixed ?

Thanks in advance !

ModuleBase                                                            Version
----------                                                            -------
C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.518.1 1.22.518.1

**Comment by andikrueger** [comment]
Comparing has still an issue. We are working on a PR for this. This PR should be ready soon.

**Comment by krugerd** [comment]
Andi, I don't have an issue running New-M365DSCReportFromCoinfiguration either.  However I wanted to point out that I (and perhaps others) always have a problem with: Uninstall-M365DSCOutdatedDependencies as it never can uninstall older versions of Microsoft.Graph.Authentication.  Not sure if this is related to others having this problem or not but thought I'd point out...

example messages:
Uninstalling Microsoft.Graph.Authentication version {1.9.5}                                                             PackageManagement\Uninstall-Package : The module 'Microsoft.Graph.Authentication' of version '1.9.5' in module base     folder 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.5' cannot be uninstalled,         because one or more other modules 'Microsoft.Graph.Applications,Microsoft.Graph.DeviceManagement,Microsoft.Graph.Device Management.Administration,Microsoft.Graph.DeviceManagement.Enrolment,Microsoft.Graph.Devices.CorporateManagement,Micros oft.Graph.Groups,Microsoft.Graph.Identity.DirectoryManagement,Microsoft.Graph.Identity.Governance,Microsoft.Graph.Ident ity.SignIns,Microsoft.Graph.Planner,Microsoft.Graph.Teams,Microsoft.Graph.Users' are dependent on this module.          Uninstall the modules that depend on this module before uninstalling module 'Microsoft.Graph.Authentication'.           At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21                          + ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters                                             +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 + CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Packag     e], Exception                                                                                                            + FullyQualifiedErrorId : UnableToUninstallAsOtherModulesNeedThisModule,Uninstall-Package,Microsoft.PowerShell.Pac     kageManagement.Cmdlets.UninstallPackage                                                                                                                                                                                                      Uninstalling Microsoft.Graph.Authentication version {1.9.3}                                                             PackageManagement\Uninstall-Package : The module 'Microsoft.Graph.Authentication' of version '1.9.3' in module base     folder 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.3' cannot be uninstalled,         because one or more other modules 'Microsoft.Graph.Applications,Microsoft.Graph.DeviceManagement,Microsoft.Graph.Device Management.Administration,Microsoft.Graph.DeviceManagement.Enrolment,Microsoft.Graph.Devices.CorporateManagement,Micros oft.Graph.Groups,Microsoft.Graph.Identity.DirectoryManagement,Microsoft.Graph.Identity.Governance,Microsoft.Graph.Ident ity.SignIns,Microsoft.Graph.Planner,Microsoft.Graph.Teams,Microsoft.Graph.Users' are dependent on this module.          Uninstall the modules that depend on this module before uninstalling module 'Microsoft.Graph.Authentication'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Packag
   e], Exception
    + FullyQualifiedErrorId : UnableToUninstallAsOtherModulesNeedThisModule,Uninstall-Package,Microsoft.PowerShell.Pac
   kageManagement.Cmdlets.UninstallPackage

Uninstalling Microsoft.Graph.Authentication version {1.9.2}
PackageManagement\Uninstall-Package : The module 'Microsoft.Graph.Authentication' of version '1.9.2' in module base
folder 'C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.2' cannot be uninstalled,
because one or more other modules 'Microsoft.Graph.Applications,Microsoft.Graph.DeviceManagement,Microsoft.Graph.Device
Management.Administration,Microsoft.Graph.DeviceManagement.Enrolment,Microsoft.Graph.Devices.CorporateManagement,Micros
oft.Graph.Groups,Microsoft.Graph.Identity.DirectoryManagement,Microsoft.Graph.Identity.Governance,Microsoft.Graph.Ident
ity.SignIns,Microsoft.Graph.Planner,Microsoft.Graph.Teams,Microsoft.Graph.Users' are dependent on this module.
Uninstall the modules that depend on this module before uninstalling module 'Microsoft.Graph.Authentication'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Packag
   e], Exception
    + FullyQualifiedErrorId : UnableToUninstallAsOtherModulesNeedThisModule,Uninstall-Package,Microsoft.PowerShell.Pac
   kageManagement.Cmdlets.UninstallPackage

**Comment by ykuijs** [comment]
@krugerd I am working on a PR that will fix the Uninstall issue. Will be included in the next release!

**Comment by krugerd** [comment]
Thanks @ykuijs !
