### ISSUE TITLE
New-M365DSCDeltaReport returns no delta information

### ISSUE THREAD

**Issue by yoinuma** [microsoft/Microsoft365DSC#1970]
#### Details of the scenario you tried and the problem that is occurring
Comparing the files output by Export-M365DSCConfiguration for two different SPO tenant level settings (CommentsOnSitePagesDisabled, SPOHubSite, LegacyAuthProtocolsEnabled, etc), the New-M365DSCDeltaReport command does not output any difference information. 

`New-M365DSCDeltaReport -Source "C:\temp\dsc\20220526Config.ps1" -Destination "C:\temp\dsc\InitialConfig.ps1" -OutputPath "C:\temp\dsc\output.html"`
![image](https://user-images.githubusercontent.com/31690455/170399333-d1960fb6-d745-4923-8ace-fbe218c1f3fa.png)
![image](https://user-images.githubusercontent.com/31690455/170399372-24acd189-99d0-4105-9908-03d397f9966d.png)

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.22.525.1
![image](https://user-images.githubusercontent.com/31690455/170399543-775ea7b9-72a8-4656-83fd-dd5b6d3b7be6.png)

**Comment by martynstar** [comment]
I am also getting similar issues.
Blueprint assessments - been struggling for a few versions now.
Have found some issues get fixed by closing the powershell window and re-opening, but as yet a Assert or delta reports do not work.

These are the errors im getting

Test-Path : Cannot bind argument to parameter 'Path' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\modules\M365DSCReport.psm1:833 char:26
+     if ((Test-Path -Path $OutputPath) -eq $false)
+                          ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Test
   PathCommand

Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size
of the collection.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\modules\M365DSCReport.psm1:475 char:9
+         $endPosition = $fileContent.IndexOf("`r", $startPosition)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

Exception calling "Remove" with "2" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\modules\M365DSCReport.psm1:476 char:9
+         $fileContent = $fileContent.Remove($startPosition, $endPositi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

<h1>Blueprint Assessment Report</h1>
<html><head><meta charset='utf-8'><title>Microsoft365DSC - Blueprint Assessment Report</title></head><body>
<div style='width:100%;text-align:center;'>
<img src='http://Microsoft365DSC.com/Images/Promo.png' alt='Microsoft365DSC Slogan' width='500' />
</div>
<p><strong>No discrepancies have been found!</strong></p>
</body></html>


I want to compare a dev environment after making changes, and also against a blueprint thats created.
If for some reason i have multiple compliance policies etc, it should match and compare all of them against the template surely?

**Comment by andikrueger** [comment]
```
Exception calling "IndexOf" with "2" argument(s): "Index was out of range. Must be non-negative and less than the size
of the collection.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\modules\M365DSCReport.psm1:475 char:9
+         $endPosition = $fileContent.IndexOf("`r", $startPosition)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException

Exception calling "Remove" with "2" argument(s): "StartIndex cannot be less than zero.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\Microsoft365DSC\1.22.525.1\modules\M365DSCReport.psm1:476 char:9
+         $fileContent = $fileContent.Remove($startPosition, $endPositi ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException
```

These errors are related to configurations that do not hold proper information about the Microsoft365DSC Version used for the export/configuration.

Please make sure to have the following line with **-ModuleVersion** within your configuration/blueprint

```powershell
Import-DscResource -ModuleName 'Microsoft365DSC' -ModuleVersion '1.22.202.1'
```

$OutputPath is a mandatory parameter. Currently the parameter misses this appropriate annotation.

**Comment by andikrueger** [comment]
That change was made to allow the conversion of configurations regardless of microsoft365dsc module version available on the system. 

could you verify that you do not have multiple versions of m365dsc installed within ps7? Please have a look at the comments within #2120.

**Comment by NikCharlebois** [comment]
Andi is correct, the ModuleVersion was removed to ensure you could compare two configurations that were using a different version of the module. Otherwise, you would have to manually update the configuration to point to the correct installed version every time an assessment was being performed. I am working on a fix that will ensure the ModuleVersion is found before attempting to strip it out. I was able to confirm that this works with both PoSh 5 and 7.1 if the module version is not specified in the files.

**Comment by mpiederiet** [comment]
Oops, my bad. Removing the old Microsoft365DSC versions in PS7 fixed it for me. I assumed this had to do with the difference in PowerShell versions, but just now I learned that only one version of the Microsoft365DSC module needs to be installed... Thanks for having a look @andikrueger and @NikCharlebois!
