### ISSUE TITLE
SPOSiteGroup: Inconsistence extraction of Permissions

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2036]
#### Details of the scenario you tried and the problem that is occurring
Running an extraction for SPOSiteGroup on a German OS will result in german group permissions. These permissions are not defined within the role definition and therefore this extracted configuration cannot be re-applied.

#### Verbose logs showing the problem

```
Role definition 'Bearbeiten' not found. 
+ CategoryInfo : WriteError: (:) [], CimException 
+ FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Principals.SetGroupPermissions + PSComputerName : localhost
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
SPOSiteGroup 72135de4-7624-4005-a55d-68bf45f0501a
        {
            Credential           = $Credscredential;
            Ensure               = "Present";
            Identity             = "Sample Team Site Members";
            PermissionLevels     = @("Bearbeiten");
            Url                  = "https://$($OrganizationName.Split('.')[0]).sharepoint.com/sites/SampleTeamSite";
        }
```

#### The operating system the target node is running
Windows 10, German.

#### Version of the DSC module that was used ('dev' if using current dev branch)
latest.

**Comment by NikCharlebois** [comment]
After much investigation, this is caused by the language of the SPO site and has nothing to do with the OS. If you export the permissions from a site that has its locale in German, the permissions names will be extracted in German. This means that they can ONLY be re-applied on a site that is in German. This is not a bug, it's the expected behavior of the system. I wouldn't expect users to extract permissions and other settings from a German site and try to replicate on a site that is only English. The SPOSite resource allows for locales to be specified and should be aligned with resources that can have locale specific settings such as the SPOSiteGroup.
