### ISSUE TITLE
EXOMalwareFilterPolicy Attribute EnableInternalSenderNotifications should be removed from Microsoft365DSC since it is only for On-Premises Exchange reserved

### ISSUE THREAD

**Issue by atdheekurteshi** [microsoft/Microsoft365DSC#2082]
**Details of the scenario you tried and the problem that is occurring**

**EXOMalwareFilterPolicy** AttributeKey : **_EnableInternalSenderNotifications_** should be removed from **Microsoft365DSC** since it is only available **on-premises Exchange**.

This cmdlet is available in **on-premises Exchange** and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the other.

[Please check this link for more information](https://docs.microsoft.com/en-us/powershell/module/exchange/set-malwarefilterpolicy?view=exchange-ps)

**Comment by andikrueger** [comment]
Please have a look at #2033. This is a know issue. Due to our Breaking Change Policy, this needs to be done in October this year.

**Comment by malauter** [comment]
These parameters are already marked as deprecated since version 1.22.629.1. They will be removed with the next breaking change release.

_Parameters Action, EnableExternalSenderNotifications and EnableInternalSenderNotifications are deprecated and will be removed in future. These parameters are no longer available in EXO, only in onprem Exchange. Please remove these parameters from your configuration._
