### ISSUE TITLE
SCSensitivityLabel: Parameter Settings needs to be renamed or DSCParser needs to support parameter named "Settings"

### ISSUE THREAD

**Issue by andikrueger** [microsoft/Microsoft365DSC#2314]
The SCSensitivityLabel resource is using a Settings parameter. This works fine when extracting the configuration, but the Delta report and Documentation generation is using the DSCParser module. That module is treating this Settings parameter incorrectly. This needs to get changed to another name, which is a breaking change.

_Originally posted by @ykuijs in https://github.com/microsoft/Microsoft365DSC/issues/1880#issuecomment-1176131503_

Changing this parameters name to `LabelSetting` should resolve the issue.

https://github.com/microsoft/Microsoft365DSC/blob/b8624c55452713cf6a487513144186cfb9689770/Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.schema.mof#L11

This change would need to be made within the module as well.

**Comment by NikCharlebois** [comment]
I have not yet done any investigation, but it may make more sense to modify DSCParser to properly handle the Settings parameter. Ideally we would like to keep the parameter set of the resources aligned with the properties of the related cmdlet.

**Comment by ykuijs** [comment]
The AST sees the Settings parameter as a Keyword, causing the DSCParser to fail. Of course we can change the DSCParser to ignore Settings being a keyword, but this is solving the symptom instead of the root cause. I prefer not using keywords as parameter.

To prevent these types of issues we can add a genetic test to the unit test. That way we detect these issue when a PR is created.
