### ISSUE TITLE
Information about properties in DSC

### ISSUE THREAD

**Issue by OlivierWaterloos** [microsoft/Microsoft365DSC#2400]
Hello,

I would like to create a Reference Architecture by using DSC. I'm looking an easy way to have the Microsoft documentation of each parameters or properties. 
The idea is to open the the html report and have the information of the parameters.
Do you think it could be possible?
Thanks
Regards

Olivier

**Comment by NikCharlebois** [comment]
Sounds like a great idea. Can you elaborate on what you mean by "documentation of each parameters or properties"? We do have the following list of components/properties available as markdown files:
https://microsoft365dsc.com/resources/azure-ad/AADApplication/

**Comment by OlivierWaterloos** [comment]
Hello Nik, Thank you for your answer.
The link you have send me is very helpful. Thanks.
The meaning of "documentation of each parameters or properties", for a DSC report in HTML, a hyperlink to the page to the associated parameter.
As an example: a hyperlink on SPOAccessControlSettings title with the address [https://microsoft365dsc.com/resources/sharepoint/SPOAccessControlSettings/](https://microsoft365dsc.com/resources/sharepoint/SPOAccessControlSettings/)

A very "nice to have" is to merge the 2 in 1 page with a personal comment (why this parameter has been choose):

                                                                   SPOAccessControlSettings			
Parameter	|	Value	|	Description					|	Allowed Values      |     IT Remarks
-------------------------------------------------------------------------------------------------------------------------------------------
Ensure		|	Present	|	Only value accepted is 'Present'	|	Present, Absent     |    Need this parameter to be enabled, I like it ;)

The personal comment could come from a ps1 file like a DSC extract with personal info:
RA_Comments.ps1:
Node localhost
    {
        SPOAccessControlSettings <ID>
        {
            Ensure                       = "Need this parameter to be enabled, I like it ;)";
        }
...}
This file is write by the IT architect or engineer.

It can be some extra parameters on the function New-M365DSCReportFromConfiguration:
New-M365DSCReportFromConfiguration -Type HTML -ConfigurationPath "$DSCPathWork\DSC_SPO.ps1" -OutputPath "$DSCPathWork\SPO.html" -IncludeDescriptions -PersonalCommentPath "$DSCPathWork\RA_Comments.ps1" 

-IncludeDescriptions = add column "description" and "Allowed Values"
-PersonalCommentPath =  path of the PS1 file with personal info

Do you think it could be possible?

**Comment by andikrueger** [comment]
Have you had a look at M365DSC blueprints? https://microsoft365dsc.com/user-guide/advanced/create-blueprint/

**Comment by OlivierWaterloos** [comment]
Thanks Andi.
The blueprints system shows you the differences between the recommande values of the blueprint file and what's implement in the tenant.
What I'm looking for is a report with what's implemented in the tenant, the definition of the parameters and a comment of our IT teams why they implemented that way.

**Comment by andikrueger** [comment]
Would the blueprint syntax work for you?

**Comment by andikrueger** [comment]
I've had a few thoughts about this. Another property for a resource doesn't make sense, because these pros only make the resource artificially complex and we would have to implement these changes across all resources at least 3 times.

Using comments (compare Blueprint) would make it possible to add an individual comment to each property of a resource. In terms of effort, reporting could be adapted more easily, since only the comments from the configurations need to be read out. This is already done today for the BluePrints.

What I have not yet tested is whether a configuration with comments can be compiled without further issues.

**Comment by martincaddick** [comment]
Sorta related, to follow on with the SPOAccessControlSettings example, I can see from https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/DSCResources/MSFT_SPOAccessControlSettings/MSFT_SPOAccessControlSettings.psm1 that we're using Get-PnPTenant to pull the information back and the result set contains 21 properties.
If I run "Get-PnpTenant | Get-Member -MemberType Property | Measure-Object" then I get 78 properties.

What determines which of those properties are usable within M365DSC?

I ask because I'm particularly interested in some of the properties for SCDLPComplianceRule (ModifySubject and AdvancedRule)

**Comment by andikrueger** [comment]
The set of parameters is usually determined what the Set-Method/Update-Method is capable of to set. Some Get-Methods expose read only parameters that cannot be changed.

**Comment by OlivierWaterloos** [comment]
Hello Andi,

The engineers was not happy to update a PS1 file as base for the Reference Architecture.
I have implement a List in a Teams where they can add comment and status of the property (Approved, Not used, deleted, New). Based on this list, and only Approved properties, a report (in a HTML format) is generated. 
It's still in a POC: still waiting the validation of the manager. :-)
Thank you for brainstorm with me about this topic. ;)
