### ISSUE TITLE
IntuneAntivirusPolicyWindows10SettingCatalog

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#2463]
# Issue Description

1 - We need to change the logic of the resource so that instead of retrieving instance by templateID, it retrieves it by TemplateFamily where = 'endpointSecurityAntivirus'

2 - For the defender configuration, the vendor_msft_defender_configuration_tamperprotection_options_0 property get converted to Options0 in the export, where it should be handled as TamperProtection or something similar.

**Comment by NikCharlebois** [comment]
@William-Francillette is this something you could take a look at if you get a chance? Thanks

**Comment by William-Francillette** [comment]
Sure, leave it with me - I'll dig into it

Is the reason that the template ID could change overtime?
As for the tamper protection, it should not be exported (by the current resource) because it's not part of the AV policy but the windows experience policy in Intune 
I was following the Intune portal to develop those resources

**Comment by William-Francillette** [comment]
Oh I see now - the templatefamily will include both policies/templateIDs

**Comment by RavennMSFT** [comment]
@William-Francillette any update on this?

**Comment by William-Francillette** [comment]
@RavennMSFT still work in progress, I should be able to deliver the resource during the weekend or early next week the latest

**Comment by William-Francillette** [comment]
It was quicker than I expected :D PR pushed
