### ISSUE TITLE
EXOHostedOutboundSpamFilterPolicy NOT FOUND in target

### ISSUE THREAD

**Issue by upaneshpatel** [microsoft/Microsoft365DSC#2492]
I'm trying to replicate policies to test tenant with EXOHostedOutboundSpamFilterPolicy. There are 2 additional policies besides "Default" which I want to replicate. Though when DSC tries to create the new policy in the target it give below error.

**_If the policy doesn't exists, shouldn't DSC try to create it? Obviously it doesn't exists in the target so I'm not sure why its trying to look for it instead of creating it?_**

**Ex6F9304|Microsoft.Exchange.Configuration.Tasks.ManagementObjectNotFoundException|The operation couldn't be performed   **because object 'Outbound SPAM max' couldn't be found on 'DM5PR04A09DC003.NAMPR04A009.PROD.OUTLOOK.COM'.****

**Comment by andikrueger** [comment]
Please provide the following information so that we can have a closer look:

- Verbose logs showing the problem
- Suggested solution to the issue
- The DSC configuration that is used to reproduce the issue (as detailed as possible)
  - insert configuration here
- The operating system the target node is running
- Version of the DSC module that was used ('dev' if using current dev branch)

**Comment by malauter** [comment]
Root-cause identified. I will work on a fix next week.

**Comment by upaneshpatel** [comment]
Thank you. 

I had the same error for **"EXOAcceptedDomain"  - The operation couldn't be performed   because object 'mibioresearch.com' couldn't be found on**

So the fix can be applied to both resources.

**Comment by malauter** [comment]
@upaneshpatel I fixed this for EXOHostedOutboundSpamFilterPolicy in the linked PR. It now supports also New- and Remove- operations.
For EXOAcceptedDomains, it is a little bit different. Since there is no New-/Remove-AcceptedDomain cmdlet in Exchange Online, we cannot add this to the DSC resource.
