### ISSUE TITLE
Export-M365DSCConfiguration : Recommended "hardware" specifcations icw -MaxProcesses argument

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2780]
Hi,

I would like to get some pointers regarding the "hardware" requirement for the Microsoft365DSC tooling to run smoothly and as fast as possible. For some of our tenants the Export-M365DSCConfiguration cmdlet takes long to complete for e.g. SPO and TEAMS workload as there are many Sharepoint sites and/or Teams sites. 

I am running this cmdlet now on a standard GH runner (with the following specs);

- 2-core CPU (x86_64)
- 7 GB of RAM
- 14 GB of SSD space

What is the default number of Processes this cmdlet spawns? I cannot find any info on that in the documentation. Would it be beneficial to increase the process count if the specs are already that low?

Any pointers (or from the field experience) would be appreciated.

**Comment by MarcelHeek** [comment]
Does this section mean that parallelism is removed from the code?
https://microsoft365dsc.com/user-guide/get-started/snapshot-of-existing-tenant/#maxprocesses

**Comment by NikCharlebois** [comment]
Yes, parallelism was removed from most resource since it introduced management complexity and had various issues with error handling. One recommendation is to leverage the new -Filters parameter for Microsoft Graph based resources and to divide the extraction into smaller export processes. We have also since some performance improvements in using PowerShell 7.3+ over 5.1.
