### ISSUE TITLE
Workload SPO/Teams with many sites/Teams takes very long to complete export

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2820]
Hi,

I am currently exporting the full SPO workload for a tenant that has 22000+ sites in the environment. Running the export takes literally many days already and still not finished. Off course I know I can scope to smaller set of component and run multiple sessions, but I would like to have a full export as a starting point to discuss with the responsible teams which components are of interest for governance and what components are relevant for periodical export which is useful for consulting the SPO configuration data at earlier points in time (e.g. weekly exports is what I am aiming for).

But the exports takes a very long time. Is there any way of speeding up the datacollection for large tenants? I know at some point there was parallelism in the code, but that appears to be disabled.

Any thoughts?

btw I am experiencing the same issue for tenants with many Teams in use. Currently waiting for an export of 9000+ teams which is already running for 2 days

**Comment by NikCharlebois** [comment]
Some of the Microsoft Graph based workloads (AAD, Intune and Planner) allow you to specify a -Filters parameter to the Export-M365DSCConfiguration cmdlet, which would allow you to export in batches (e.g., by OU). Unfortunately for other workloads, there isn't a way to break it down in that fashion. The multi-parallelism was removed from some resources due to issues with PowerShell 7 and how it was being handled and we don't have plans to re-introduce it. We are open to suggestions, but as it currently stands there are unfortunately no ways to achieve this.

**Comment by MarcelHeek** [comment]
@NikCharlebois Just a thought. Can parallelism not be available only for PowerShell 5.1 sessions and disregarded (with STDOUT warning notification) when running on PowerShell 7.  This gives us the option to choose whether to run a task on the version that will benefit runtime (v5.1) and choose v7 for the rest.

I reckon that in time the focus might move away from PoSh 5.1 support and v7 might become the main prerequisite, but I guess that point is not in the near future.
