### ISSUE TITLE
Full support for PowerShell 7+

### ISSUE THREAD

**Issue by MarcelHeek** [microsoft/Microsoft365DSC#2849]
Hi,

I was wondering what the timeline would be for the support for PowerShell 7+ for the DSC module (and depending modules). Last reference in the closed issues is a while back, and I guess work might have been done in the area to get the modules available for PowerShell 7+.

Is there any information if it will be supported and possible when we can expect it to become supported.

It would be very beneficial for us as I run all sorts of Powershell scripts on linux based GH runner. I guess not all functionality, like drift detection, would be available then, but nevertheless I would be interested to run e.g. the exports on linux based (self-hosted) GH runners.

**Comment by andikrueger** [comment]
Please have a look at this documentation article: https://microsoft365dsc.com/user-guide/get-started/powershell7-support/

At the moment there are some more requirements due to the used modules within M365DSC. Some of the other PowerShell modules do require native Windows dlls. Running the solution on a linux worker would not work. This a dependency we cannot solve on our own and are up to the other modules owners.

**Comment by MarcelHeek** [comment]
Ok, thanks for the answer and I will look into building a dedicated Windows based self-hosted GitHub runner then.

**Comment by shingotoda** [comment]
Hello, what is the current state of PowerShell 7 support? What does the Pending Information label mean?
