### ISSUE TITLE
When we try to open repo as close in vs code it prompts for Select repository destination, but in document it says select repository location

### ISSUE THREAD

**Issue by s4vishwa** [microsoft/Microsoft365DSC#2916]
![image](https://user-images.githubusercontent.com/42575304/219413916-0b52ee84-fa9d-40ca-bebf-092efe7ef7a7.png)

    Your feedback and support is greatly appreciated, thanks for contributing!

    ISSUE TITLE:
    Please prefix the issue title with the resource name, e.g.
    'ResourceName: Short description of my issue'

    ISSUE DESCRIPTION (this template):
    Please provide information regarding your issue under each header below.
    Write N/A under any headers that do not apply to your issue, or if the
    information is not available.

    NOTE! Sensitive information should be obfuscated.

    PLEASE KEEP THE HEADERS.

    You may remove this comment block, and the other comment blocks,
    but please keep the headers.
-->
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by andikrueger** [comment]
could you please share to which documentation you are referring to? Thanks!

**Comment by s4vishwa** [comment]
[Managing Microsoft 365 with Microsoft365Dsc and Azure DevOps.pdf](https://github.com/microsoft/Microsoft365DSC/files/10766654/Managing.Microsoft.365.with.Microsoft365Dsc.and.Azure.DevOps.pdf)

**Comment by ykuijs** [comment]
The new version of the whitepaper has been published this morning! It took a little bit longer due to some other improvements and bugs we encountered during testing. My apologies for that!

You can find the announcement [here](https://twitter.com/Microsoft365DSC/status/1849354214528422028) and the new version of the whitepaper [here](https://aka.ms/m365dscwhitepaper).

Closing this issue now, since it is no longer relevant for the new whitepaper.
