### ISSUE TITLE
PROPOSAL: Extraction Process Improvement

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#3009]
### Description
The goal of this proposal is to improve the overall performance of the Extraction process. Currently, the Export-M365DSCConfiguration cmdlet calls into the Export-TargetResource function of every resource selected. The Export-TargetResource starts by retrieving all instances of a given resource (e.g., all Azure AD Users in the tenant). It then loops through each instances and calls the Get-TargetResource function with the primary key of the instance. The Get-TargetResource instance then in turns makes an additional call to retrieve the given instance based on its primary key, de-doubling the number of calls across the wire.

Our proposal is to prevent the Get-TargetResource function from retrieving the instances a second time since the Export-TargetResource function already have its related data in "memory" and have it pass all the data associated to the instance to the Get-TargetResource directly instead.

### Proposed properties
Add a new $IsExport boolean property to all resource. Then have the Export-TargetResource populate the properties associated to the instance and pass them to the Get-TargetResource function directly instead. Inside of the Get-TargetResource, we will need to add a condition that checks if IsExport is true, and have it bypass the subsequent call to retrieve the given resource's instance.

### Special considerations or limitations
We could begin by implementing this change on selected resources only and then expand to all resources. E.g., AADUser, AADGroup, SPOSite, EXOMailbox (upcoming), etc..

**Comment by NikCharlebois** [comment]
As a test, this change was implemented on the AADUser resource. Preliminary benchmark show a 17% speed improvement for an environment having 4,200 users. Performance improvements will be exponential in relation to the number of items being retrieved and will be more significant where higher numbers of instances are being retrieved.

**Comment by DeyvLauzon** [comment]
HI Everyone, 

this improvement is very important to us. From my testing it has a major impact. For 80000 mailbox it takes me 30 hours or under 1 hour if I don't have to redo a get-mailbox for each one. 

And to me it makes a lot of sense of not using a another get- command for something we already have in the initial global get.

Thank you for all your work

**Comment by ykuijs** [comment]
I definitely understand the need to increase performance, but don't like the idea to add a parameter that is only used by our export code.

Is it possible to add this parameter without adding it to the schema? That way it isn't exposed to end users. Or if that is not possible set the user object in a Global variable which is then checked and used in the Get method instead of retrieving this from M365?

**Comment by andikrueger** [comment]
Would it be possible to reuse this globale variable for this purpose:

$Global:CurrentModeIsExport

This variable is already in the code and could be used for this scenario.

**Comment by ykuijs** [comment]
Two thoughts:
- There might be parameters that need some formatting because the value in the object isn't what we present to the user. This would mean that the Export method has to do some data manipulation (just like the Get method does) before inserting that into the Get method and we need to maintain that logic in two places.
- I might miss something, but if we just insert the values from the object into the Get method, I do not see why we use the Get method and don't format the data directly in the Export method.

My preference:
My idea with the Global variable would be to place the user object in that variable. The Get method then would check if that variable exists and if so, use the data in there instead of retrieving it from M365. That way the rest of the logic in the Get method would be exactly the same and we only need to change the data retrieval part.

**Comment by andikrueger** [comment]
We could do all manipulations in a separate method that would either be called from get- or export-

this method would need to deal with all parameters though. 

Any chance to use $script variables to store the data? This way we would not overpopulate the global scope.

**Comment by ykuijs** [comment]
The script variable is a good idea to test. Could work perfectly (which I expect it will) and will be a perfect alternative if it does.

**Comment by salbeck-sit** [comment]
I'll second @ykuijs's comment about 'formatting'. For some resources, certain properties are based on relationships to other objects. However, agree that it would save time if an Export 're-uses' retrieved objects in Get-TargetResource. So, if a resource requires fetching relationships those calls would still be required, but resources that doesn't would certainly speed up the export.
Another option could be for Get- and Export-TargetResource to call the same internal function for formatting the resource if it turns out that all Get-properties must exist in the schema. That way the schema is kept clean. Perhaps somewhat tedious to code for existing resources but much easier with the DRG going forward.

**Comment by NikCharlebois** [comment]
Have a look at the PoC:
https://github.com/NikCharlebois/Microsoft365DSC/blob/Export-PerformanceImprovements/Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1#L165

**Comment by andikrueger** [comment]
@NikCharlebois Am I missing something. Within the POC I do not find a proper assignment for the $user object. This will only be assigned, if Get-MGUser is used. Get-MGUser will only be called in non-export scenarios.

**Comment by NikCharlebois** [comment]
If the mode is Export, then we take the values from the PSBoundParameters received from the Export-TargetResource function directly

**Comment by andikrueger** [comment]
Understood. I see the if… https://github.com/NikCharlebois/Microsoft365DSC/blob/a9cd430ed53e11920e472055338042ea8c2e42d9/Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1#L165

What I do not find, is the implementation to assign the user variable with the bound parameters in an else block.

**Comment by NikCharlebois** [comment]
Gotcha, yes, there should indeed be an else clause where we would populate a user object based on PSBoundParameters.
