### ISSUE TITLE
New-M365DSCDeltaReport: incorrect unique attribute

### ISSUE THREAD

**Issue by spiderchicke2** [microsoft/Microsoft365DSC#3081]
Hello everyone,

Can you please check if there is an issue with New-M365DSCDeltaReport when comparing AADApplication recource?
report is generated but it seems that it uses "DisplayName" attribute for comparison. as a result we may see incorrect output if there are 2 applications with the same DisplayName, which is not prohibited.

please see result:
<html>
<body>

<table width="100%" cellspacing="0" cellpadding="5">
<tbody><tr>
<th style="width:25%;text-align:center;vertical-align:middle;border:1px solid black;;" rowspan="5"><img src="http://microsoft365dsc.com/Images/AzureAD.jpg">
</th>
<th style="border:1px solid black;text-align:center;vertical-align:middle;background-color:#CCC" colspan="3">
<h3>AADApplication - DisplayName = SYSTRAN</h3>
</th></tr>
<tr>
<td style="text-align:center;border:1px solid black;background-color:#EEE;" width="45%"><strong>Property</strong></td>
<td style="text-align:center;border:1px solid black;background-color:#EEE;" width="15%"><strong>Source Value</strong></td>
<td style="text-align:center;border:1px solid black;background-color:#EEE;" width="15%"><strong>Destination Value</strong></td>
</tr>
<tr>
<td style="border:1px solid black;text-align:right;" width="45%">
AppId</td>
<td style="border:1px solid black;" width="15%">
931bddb8-c0fe-47a0-9cfe-07182bc959e9</td>
<td style="border:1px solid black;" width="15%">
c84ec7c9-29d3-4ccb-a0ce-a8f8ddc2ec05</td>
</tr>
<tr>
<td style="border:1px solid black;text-align:right;" width="45%">
IdentifierUris</td>
<td style="border:1px solid black;" width="15%">
https://$OrganizationName/d7b3cf83-2b28-498c-b495-06ab8386856c</td>
<td style="border:1px solid black;" width="15%">
https://$OrganizationName/78c56289-ec0b-499a-889f-8feae477f629</td>
</tr>
<tr>
<td style="border:1px solid black;text-align:right;" width="45%">
ObjectId</td>
<td style="border:1px solid black;" width="15%">
9831ecad-7eca-4824-a47c-724d382a9f91</td>
<td style="border:1px solid black;" width="15%">
49a09d3b-df73-4065-b803-2b99aa308270</td>
</tr>
</tbody></table>

</body>
</html>

AADServicePrincipal  recource is being compared by AppID attribute, which is unique and there is no issues.

Thank you

**Comment by andikrueger** [comment]
Please review #2006 for further information related to this issue. Right now, we do not plan to change the key parameters.

**Comment by NikCharlebois** [comment]
While we completely understand that due to circumstances out of their control, organizations will sometimes end up having multiple instances of resources with the same display name, we do not consider it best practice (unless you can provide a business justification which we would love to better understand). We need to use the DisplayName property as a primary key to support the scenario where customers want to clone the configuration of a tenant onto another one. off course, the logical primary key would be the AppID, but folks writing a configuration for a new environment from scratch would not be able to provide an AppID before it actually gets created (chicken and egg).

Our recommendation would be to use this report as a way to identify areas that need cleaning (multiple apps with the same display name) or clean the configuration manually to remove duplicates, which we understand is unfortunate.
