### ISSUE TITLE
FalsePositive due to quotation mark in parameters.

### ISSUE THREAD

**Issue by maheshdalavi** [microsoft/Microsoft365DSC#3165]
#### Details of the scenario you tried and the problem that is occurring
-	Some values like: NotifyPolicyTipCustomText, NotifyEmailCustomText and Comment as Quotation marks.
-	I am getting a FalsePositive for Drift monitoring.
-	In M365Tenantconfig.PS1, Quotation Mark’s is added with ( Grave Accent character ). 
-	Screenshot from M365Tenantconfig.PS1
![image](https://user-images.githubusercontent.com/22946692/231764274-f6bffb74-fa2c-4187-b4fb-7f6c0ea7a97e.png)

-	This value is replaced as \“DNF or Restricted\” in Localhost.mof file 
-	Eventually, this results in FalsePositive in drift monitoring, Because this is replaced by **“left/right double quotation marks**” in DSC parsing. 
#### Verbose logs showing the problem
Below are the screenshots from the Event viewer.
 
![image](https://user-images.githubusercontent.com/22946692/231764111-5cea183e-5925-4062-87cb-4a9f6ac0c8b1.png)

==============
 
![image](https://user-images.githubusercontent.com/22946692/231764150-d0b9c3ca-4805-4c94-b2cd-a0fe5a4ae173.png)

#### Suggested solution to the issue
use of raw encoding for affected values. even single quotation mark or inverted comma can be problematic 
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

**Comment by NikCharlebois** [comment]
Just to confirm, we are only able to reproduce if the **current value** in the Compliance center is using these tilted double quotes. If the original message doesn't use them or if you manually update the config file to include the tilted quotes, then it works. We have code to ensure invalid tilted characters are removed at extraction because of various encoding issues we've had in the past.
https://github.com/microsoft/Microsoft365DSC/blob/Dev/Modules/Microsoft365DSC/Modules/EncodingHelpers/M365DSCStringEncoding.psm1#L31
