### ISSUE TITLE
Build.ps1 fails when using latest version of M365DSC with AzureDevops

### ISSUE THREAD

**Issue by martinisoft1** [microsoft/Microsoft365DSC#3838]
### Description of the issue

When using the latest version of M365DSC in conjunction with the procedure as described in the Devops Whitepaper the build.ps1 fails with the following error:

PSDesiredStateConfiguration\node : The module 'SecurityCompliance' could not be loaded. For more information, run 'Import-Module SecurityCompliance'.

This is not the case when running  1.22.1019.1
Is there something in the composite resources that needs to be updated? Or how what can I do to be able to run the latest version?

Thanks in advance,

Martijn.

### Microsoft 365 DSC Version

1.23.1025.1

### Which workloads are affected

Security & Compliance Center

**Comment by kochi-shunsuke** [comment]
I am facing the same issue.
I also want to know how to solve it.

**Comment by andikrueger** [comment]
@ykuijs Could you have a look at this issue?

**Comment by ykuijs** [comment]
As specified in our [Breaking Changes Policy](https://microsoft365dsc.com/concepts/breaking-changes/), we are releasing breaking changes to Microsoft365DSC twice a year: In April and October.

With the [April 2023 release](https://microsoft365dsc.com/blog/april-2023-major-release/index.html), we released many breaking changes that are causing this issue. In order to fix them, you need to update the Composite Resources included in the whitepaper scripts to remove all parameters that are removed in that release.

FYI:
I am currently working on several big improvements, which I plan to document in a new version of the whitepaper. One major update is a Composite Resource Generator that is using generated versions of the composite resources module linked to each  version of Microsoft365DSC.
Currently I do not have an ETA of this update yet, since we are in the middle of implementing all enhancements. But I hope to release it asap. Keep an eye on the [Microsoft365DSC Twitter/X account](https://twitter.com/Microsoft365DSC) for updates!

**Comment by ykuijs** [comment]
The new version of the whitepaper has been published this morning! It took a little bit longer due to some other improvements and bugs we encountered during testing. My apologies for that!

You can find the announcement [here](https://twitter.com/Microsoft365DSC/status/1849354214528422028) and the new version of the whitepaper [here](https://aka.ms/m365dscwhitepaper).

Closing this issue now, since it is no longer relevant for the new whitepaper.
