### ISSUE TITLE
Clarify Requirements for Use - Prerequisites and PowerShell 7

### ISSUE THREAD

**Issue by jreinhardtproarch** [microsoft/Microsoft365DSC#4010]
Can you clarify in the prerequisites page whether this tool needs to run as administrative rights? It seems that a recent update added a warning that says "Warning {Cannot export Local Configuration Manager settings. This process isn't executed with Administrative Privileges!}" if the module is run without admin rights. I am confused about it, and don't believe it was always the case. Can you clarify?

**Comment by jreinhardtproarch** [comment]
Thank you Andi, I have had issues in both PowerShell 5.1 and 7 with the admin rights being asked for. But it isn't consistent. The code that seemed to generate the message line 863 is from a simple conditional in line 827 in https://github.com/microsoft/Microsoft365DSC/blob/98c59324ff84d077349aebfb3ee1630dc0bf81fc/Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1. It would suggest that it is always required, perhaps. Though I haven't exhaustively reviewed the particular module.

**Comment by andikrueger** [comment]
Having this as a requirement would cause additional issues or blockages for other users. M365DSC can be used for exports without having local admin rights (and tenant global admin rights). We support to install the module within the current user scope for exports. 

For applying configurations it’s required to have local admin rights to be able to send the configuration to the LCM.

**Comment by sjennings1986-1** [comment]
Hello,

I am just starting off with M365DSC and I have gone through quite some heck trying to get it setup.

I dont feel there is any clear statement of how to configure the app registration, I was able to run 
a.	$result = Get-M365DSCCompiledPermissionList -ResourceNameList (Get-M365DSCAllResources)
b.	$result.Read | ForEach-Object { "{0,-10} ({2,-11}) - {1}" -f $_.API,$_.Permission.Name,$_.Permission.Type } 

to collect the full permissions required, however, my app registration says it can only handle 30 permissions since it has multitenant configured (this could have been stated in the requirements)

Through about 4 hours of troubleshooting different Powershell module failures, I was finally able to get an export-m365dscconfiguration to run, using an AAD account @onmicrosoft and no MFA. This is inconsistent as when I try to now run this on my Server that runs as a hybrid worker for the automation account, its just running along a long list of mggraph module failures. I then try it on my personal laptop, it fails on powershell save-credential function.

It feels like this is not a well thought out solution delivery quite yet, but anyways, these are my notes that should be addressed, as I am not a new azure/code guy, this has been quite frustrating.

**Comment by jreinhardtproarch** [comment]
@andikrueger,

Is this statement still correct?

"PowerShell version[¶](https://microsoft365dsc.com/user-guide/get-started/prerequisites/#powershell-version)
Microsoft365DSC is supported for PowerShell version 5.1 and 7.3+. For additional details on how to leverage it with PowerShell 7, please refer to our [PowerShell 7+ Guide for Microsoft365DSC](https://microsoft365dsc.com/user-guide/get-started/powershell7-support/)."

I cannot get it to work in PowerShell 5.1 as it seems to depend now on DSC 2.0 which does not support Windows PowerShell 5.1. 

I would also to reset the table that the issue of admin rights is also not clear, and perhaps the issue of admin rights has something to do with DSC 2.0 as well. I am not sure, but I also am not getting a sense that there is good support so maybe this issue should be just closed...Don't want to be a burden.

**Comment by andikrueger** [comment]
@sjennings1986-1 thank you for your valuable feedback. Did you have a look at this cmdLet for updating the permissions of an AAD app registration:
https://microsoft.github.io/Microsoft365DSC/user-guide/cmdlets/Update-M365DSCAzureAdApplication/

@jreinhardtproarch at the moment, we support PS 5.1 and 7.3 , however  it’s recommended to apply an configuration with PS 5.1 (DSC V1).

**Comment by jreinhardtproarch** [comment]
Thank you for now. I am okay with the issue being closed as far as I am concerned. Perhaps a new issue can be made by @sjennings1986-1 if needed beyond your last reply. Thank you.
