### ISSUE TITLE
Issue #4394 not resolved - All my group has been duplicate

### ISSUE THREAD

**Issue by kevin14389** [microsoft/Microsoft365DSC#4508]
I am currently using the 1.24.313.1 version and this issue is still present. All my group has been duplicate.

_Originally posted by @kevin14389 in https://github.com/microsoft/Microsoft365DSC/issues/4394#issuecomment-2019969209_

**Comment by andikrueger** [comment]
Could you please share some more information about the issue and how we can reproduce on our end?

**Comment by eriel369** [comment]
is there a ' in the displayname of the group ? I have had this issue with apostrophes.

**Comment by kevin14389** [comment]
No, we have no ' in the displayname, just an hyphen. 

How to reproduce this problem : 

- We export all the group 
- We manually change the DisabledPlans when the AssignedLicences is not null in the previous created .PS1 file
- We save the .ps1 file
- We execute the .ps1 file to create the .mof
- We apply the new .mof file with Start-DscConfiguration -Path *Folder Created With Previous Step*

This was working perfectly before.

**Comment by sp1ti** [comment]
I was a bit impatient and ignored the warnings from the test run (hoping it was due to something else) --> also got me some duplicated groups. I do have IDs in the config but to different tenants so I'm falling into a only partially corrected "fix" via https://github.com/microsoft/Microsoft365DSC/pull/4370/files#diff-21e85585dbcfad3a814015a305f2c306a15cf27bc860e2b6d321c1142329d500 is wrong.

https://github.com/microsoft/Microsoft365DSC/blob/6d738942659011375039fb571635ef95ce5e092e/Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1#L150-L151
this should look like the other fix from [NikCharlebois](https://github.com/NikCharlebois)
https://github.com/microsoft/Microsoft365DSC/blob/6d738942659011375039fb571635ef95ce5e092e/Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1#L169-L173
