### ISSUE TITLE
Step by step how to check your m365 tenant for config drift. 

### ISSUE THREAD

**Issue by jbradley419** [microsoft/Microsoft365DSC#4601]
Could someone please show step-by-step how to check your tenant for config drift? So far I have exported the tenant config using the  Export-M365DSCConfiguration command.  How do I set this as my baseline and scan for changes? 

Thank you

**Comment by apcsb** [comment]
There is no "one-size-fits-all" tutorial here, since there are too many ways to use the M365DSC. The general logic will be the same. Here's how I see it.

####  If you run M365DSC in a persistent mode (LCM on a constantly running VM)

In the easiest scenario, you just configure the LCM to **ApplyAndAutocorrect** and let it take care of the drift for you.
If you need a more complex process (reviews/approvals, integration/pipeline etc) - set the LCM to ApplyAndMonitor and track the EventLog entries in any way you like (Azure Monitor, local script - whatever).
Just follow this article: https://microsoft365dsc.com/user-guide/get-started/monitoring-drifts/

#### If you run M365DSC in a non-persistent mode (LCM set to ApplyOnly - container or something similar)
You'd have to detect drift yourself. What you choose (pipeline, scheduled task etc) is up to you. Basically, you'll take a snapshot and use the https://microsoft365dsc.com/user-guide/cmdlets/New-M365DSCDeltaReport/ . It supports JSON mode and can compare against another snapshot or a Blueprint (https://microsoft365dsc.com/user-guide/advanced/create-blueprint/ ), the latter probably making more sense for you, since you can convert a config to a blueprint after a successful push.
Then you basically check if your JSON shows any drift and decide on the rest of your process (auto-push, ask for approval etc) based on what you need.

Hope this helps

**Comment by andikrueger** [comment]
Thanks @apcsb for the great summary
