### ISSUE TITLE
Request for a Filter Option for AzureAD Attribute 'AADGroup'

### ISSUE THREAD

**Issue by jj4152** [microsoft/Microsoft365DSC#4928]
### Description
We would like to request a filter option for the AzureAD attribute 'AADGroup'. This feature should enable users to filter between different group types, allowing them to export only specific groups, such as Security or M365 Groups, from AzureAD.

### Proposed properties
In addition to the existing 'AADGroup' attribute, we propose introducing two new attributes: 'AADGroupSecGrpOnly' and 'AADGroupM365GrpOnly'. The 'AADGroupSecGrpOnly' attribute would export only AAD Security Groups, while the 'AADGroupM365GrpOnly' attribute would export only AAD M365 Groups. 

A filter option would be highly beneficial, as it would allow users to avoid exporting all the AAD M365 Groups that are automatically created with the creation of all the Teams. This enhancement would streamline the export process by targeting only the necessary groups.

### Special considerations or limitations
thank you!
![eithe](https://github.com/user-attachments/assets/b40d0e40-fbfb-4f30-b1d4-bdeb8a3dc91e)

**Comment by FabienTschanz** [comment]
@jj4152 I'm sorry for the silly question, but is this for the "Download groups" button in the Entra ID Portal > Groups, right? If yes, then I think this repository isn't the correct one to place this feature request, since this here is for Microsoft365 Desired State Configuration and not the Portal itself. If you want some help in exporting the current groups for having them as a configuration, then we can provide you with help. 

The place for feedback on the Portal is here: [Entra Portal Feedback](https://feedback.azure.com/d365community/forum/22920db1-ad25-ec11-b6e6-000d3a4f0789).

**Comment by jj4152** [comment]
Hi Fabien, thank you so much for your help. Just to clarify, I’m referring to the M365DSC-Export Portal (https://export.microsoft365dsc.com/), not the Microsoft portal.

Currently, for AADGroups, there's only one attribute available for Exports. It would be incredibly helpful if we could differentiate between Microsoft 365 and Security AAD groups, similar to how it's done in the Microsoft portal. Thats why i used the screenshot from the Portal. :)

Instead of just having the single attribute “AADGroup” (as shown in the screenshot below), we would greatly appreciate it if two attributes could be added: “AADGroupSecurity” and “AADGroupM365.”
![image](https://github.com/user-attachments/assets/db4e9995-79b5-4db0-b2b4-e2e09349fa21)

This change would allow us to avoid exporting automatically generated groups, such as those created when Teams are set up, which we do not need. Thank you for your time and consideration!

**Comment by FabienTschanz** [comment]
@jj4152 Alright, now I understand what you mean. First a bit of clarification: The attribute `AADGroup` you mentioned is actually a resource type, not an attribute. An attribute would be a property on the resource, e.g. `DisplayName` or `SecurityEnabled`. That's why I didn't quite understand what you meant at first. 

But now to the good thing: You can easily filter out only security groups from the export using the `-Filter` argument in the command `Export-M365DSCConfiguration`. Following an example: 

```powershell
Export-M365DSCConfiguration -Components @("AADGroup") -Filters @{AADGroup = "SecurityEnabled eq true"} -Path "D:\Exports\AADGroup" -ApplicationId $clientId -TenantId $tenantName -CertificateThumbprint $certThumbprint
```

This command exports the resource type `AADGroup` and uses the filter `SecurityEnabled eq true` for that resource type. In the console, this looks something like the following: 
![image](https://github.com/user-attachments/assets/3853ceab-c171-4fb8-895e-9e81d36bb5b9)

I do have some other groups in my test tenant, but they are M365 groups and not security groups. Using the filter, we can exclude them from the export, and they won't be managed by M365DSC. 

Does that help you with exporting only the subset of groups that are security groups? Of course, you could turn it around and only export M365 groups, just switch the filter from `true` to `false`.

**Comment by jj4152** [comment]
Oh, my apologies—I should have looked into it first. Thanks anyway; it's working perfectly now!

**Comment by FabienTschanz** [comment]
Awesome, glad to hear you got it working. Do you mind closing the issue if it's ok for you?

**Comment by jj4152** [comment]
Hii again! :) I hope you're doing well! I have a quick question regarding some filters I've been working with. Most of them are working great, but I'm running into an issue with the filter for "AADUser - onPremisesSyncEnabled == No".

Although I have cloud-only users in my tenant, I'm not seeing any results when I export, and I don't receive any error messages either. Interestingly, when I use Microsoft Graph with the same filter, it works perfectly.

To provide some context, I'm connecting to Microsoft Graph with the following scopes: User.Read.All, and I'm filtering for users where onPremisesSyncEnabled is set to true. I’m also retrieving properties like userPrincipalName, onPremisesSamAccountName, and onPremisesSecurityIdentifier.

To show that I do have cloud-only users, I've attached a screenshot as proof:
![onpremusers yes](https://github.com/user-attachments/assets/8d17c895-dd6f-43a5-ad1a-4d49fae5578f)

And here's a screenshot showing that the export returns no results:
![2](https://github.com/user-attachments/assets/7f44e0d0-b6db-47f1-8231-a758aaac5bfa)

Any insights or suggestions would be greatly appreciated. Thank you so much for your help!

**Comment by FabienTschanz** [comment]
@jj4152 The `onPremisesSyncEnabled` property is not always filled out. You can inspect the filter queries in the Entra portal using the developer tools of your browser (F12 in Chromium browsers, don't know in others). There, I saw the following filter sent to the Graph API when selecting "On-premises sync enabled == No": 
`onPremisesSyncEnabled ne true` 

So it's actually not `eq false` as the query, it's rather `ne true`, meaning that also empty values are included.

**Comment by jj4152** [comment]
Thank you so much!!
