### ISSUE TITLE
IntuneDeviceCompliancePolicyWindows10：the import error of TpmRequired

### ISSUE THREAD

**Issue by susan-nec** [microsoft/Microsoft365DSC#5047]
### Description of the issue

Importing ps1 file always reports an error regardless of whether TpmRequired is set to true or false.
error info is : The property 'tPMRequired' does not exist on type 'microsoft.management.services.api.windows10CompliancePolicy'.
Please refer to the image for detailed information.

![error-TpmRequired](https://github.com/user-attachments/assets/57a18a44-57ca-4a22-93f8-38b8a82abe2a)

### Microsoft 365 DSC Version

1.24.904.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell
TpmRequired = $True;
or
TpmRequired = $False;
```

**Comment by FabienTschanz** [comment]
Maybe it is because the command we use in the DSC module requires you to have it written correctly (so `TpmRequired`). Just checked it with my machine, and it works fine, but I do have the latest checked out version from the repository with some additional fixes. Please stay tuned for the new release, where all the fixes are incorporated. 

In the meantime, could you share an export of your configuration here and not just the failure snippet?

**Comment by susan-nec** [comment]
Sorry for the late reply due to vacation.
Thank you very much for fixing the code. I will try it again on the latest version.
If it still cannot be imported normally, the exported parameters and evidence will be provided again.

**Comment by susan-nec** [comment]
@andikrueger  We have successfully imported the item on the latest version. Thanks a lot!

**Comment by FabienTschanz** [comment]
@susan-nec Glad to hear you got it working. Can you please close the issue? Thank you.
