### ISSUE TITLE
SInt32Array[] properties not defined correctly in respective MOF files

### ISSUE THREAD

**Issue by ricmestre** [microsoft/Microsoft365DSC#5368]
### Description of the issue

@FabienTschanz While looking at that issue I reported with DSCParser I noticed you created some MOFs where some properties were defined as *SInt32* whereas they should have been defined as *SInt32Array[]* instead, here's a screenshot below. Could you please correct these resources?

![Image](https://github.com/user-attachments/assets/0fb49b6b-4593-4e64-98c4-13799d21de20)

### Microsoft 365 DSC Version

1.24.1106.1

### Which workloads are affected

Intune

### The DSC configuration

```powershell
N/A
```

### Verbose logs showing the problem

```powershell
N/A
```

### Environment Information + PowerShell Version

```powershell
Win11/PS5.1
```

**Comment by ricmestre** [comment]
Actually you don't need to change these properties, *SInt32* is the correct type, but it uncovers 2 problems.

First, the documentation for these resources in the screenshot report that the datatype is *SInt32Array[]* even when the properties are defined in the respective MOFs as *SInt32* which means the doc generator needs to be fixed.

Second, DSCParser inspects these properties and thinks that the datatype is *SInt32Array[]* which is incorrect and it also must be fixed.

EDIT: Should think a little bit more before hitting the button, probably we should leave the doc generator alone, my code relies on reading those docs and as an example the string arrays (which have their own datatype StringArray[]) I split the values by comma, for an array of SInt32 if we change the datatype then I won't know if the values are supposed to be split unless I check if the value has commas. Same happens for *UInt32*, let's just leave the doc generator alone but DSCParser should be fixed.

**Comment by FabienTschanz** [comment]
I'll take a look at it and check what the correct type of the properties should be. It's possible that the Resource Generator misgenerated them and I didn't catch it.

**Comment by FabienTschanz** [comment]
So I got to the following conclusion: 

* `IntuneAppAndBrowserIsolationPolicyWindows10` - The property `PrintingSettings` is defined as SInt32[], which is correct.
* `IntuneAppAndBrowserIsolationPolicyWindows10` - The property `PrintingSettings` is defined as SInt32[], which is also correct.
* `IntuneDeviceControlPolicyWindows10` - The property `AccessMask` is defined as SInt32[], which is also correct.
* `IntuneFirewallPolicyWindows10` - The property `EnablePacketQueue` is defined as SInt32[], which is also correct.
* `IntuneFirewallPolicyWindows10` - The property `IPsecExempt` is defined as SInt32[], which is also correct.
* `IntuneFirewallRulesPolicyWindows10` - The property `Profiles` is defined as SInt32[], which is also correct.

The generated code is correct, as is the documentation for it. The MOF format should also be correct, according to the documentation here: https://learn.microsoft.com/en-us/windows/win32/wmisdk/mof-arrays

Did I misunderstand something? I know that some properties that should actually be string arrays are defined as a single string, with the values separated by a comma. Also, I'm using SInt32 because there could potentially be negative values and I have to consider that when generating the resource. I could do a potential analysis of the associated values and its range and decide upon that, but I think that would be too much. 

Agree that the DSCParser has to handle this case. Let's discuss that over at https://github.com/microsoft/DSCParser/issues/56.

**Comment by ricmestre** [comment]
Quick fix, https://github.com/microsoft/DSCParser/pull/57

I'll close this once the PR is merged.
