### ISSUE TITLE
EXOTransportRule

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#564]

**Comment by RobBiddle** [comment]
@malauter have you already started working on this? If not, do you mind if I take the assignment? I have an immediate need to get some automation in place for Transport Rules.

**Comment by malauter** [comment]
@RobBiddle feel free to take. I already started working on this task some months ago but due to other workloads I am not able to complete this at the moment. Would highly appreciate if you could create this important resource :) 
If you want, feel free to use my previous work on the transport rule resource: https://github.com/malauter/Office365DSC/tree/EXOTransportRule/Modules/Office365DSC/DSCResources/MSFT_EXOTransportRule

**Comment by RobBiddle** [comment]
Awesome, looks like you already did a lot of the painful work. Thanks!

**Comment by NikCharlebois** [comment]
@RobBiddle, any updates on this module?

**Comment by RobBiddle** [comment]
I've made the few updates needed to mesh with the overall refactor and tested it against some scenarios. I'm guessing you'll want more test cases. 

I just merged in the upstream but haven't tested since. 
Here's my branch: https://github.com/RobBiddle/Office365DSC/tree/RobBiddle_EXO_TransportRule

**Comment by NikCharlebois** [comment]
@RobBiddle any chances you could submit that in a PR?

**Comment by RobBiddle** [comment]
@NikCharlebois yep, here you go: https://github.com/microsoft/Microsoft365DSC/pull/1138

**Comment by NikCharlebois** [comment]
Wow, I think that resource definitively takes on the title of being the resource with the most parameters :) Thanks @RobBiddle. Few comments in Reviewable. Essentially EXO resources now need to support Azure AD Application auth (CertThumbprint, TenantID, AppID, CertSecret). Let me know if you need help with this
