### ISSUE TITLE
Assert-M365DSCTemplate issues

### ISSUE THREAD

**Issue by stevemsaunders** [microsoft/Microsoft365DSC#616]
Issue: Trying to run Assert-M365DSCTemplate results in multiple errors (see attached images)

Background:
0) Using GlobalAdmin account with MFA enabled on O365; PS window opened with administrator rights
1) Setup goes fine, albeit with some "unapproved verbs" errors ; also, no entry appears for M365DSC in local EventViewer
2) Multiple errors reported on SPO template
3)  for Teams template  "Connecting to remote server admincal.online.lync.com failed..." - ????
4) The individual with the GlobalAdmin rights was screensharing his session with me over Teams  (don't know if this is important), so apologies for the photo quality in advance

See images for details

![M365DSC troubleshoot1](https://user-images.githubusercontent.com/5722808/83290609-e0726500-a1b4-11ea-9459-c50f7dc888ed.PNG)
![M365DSC troubleshoot2](https://user-images.githubusercontent.com/5722808/83290628-e7997300-a1b4-11ea-9812-160ae2df676e.PNG)
![M365DSC troubleshoot3](https://user-images.githubusercontent.com/5722808/83290647-f08a4480-a1b4-11ea-83d7-5f76f0e3078b.PNG)

**Comment by NikCharlebois** [comment]
Hey Steve. We are investigating this. In the meantime, quick question: Did you perform an extract of your configuration already? An alternative while we nail down the assert issue is to do an export of your tenant's config, to download the blueprint and to use the **New-M365DSCDeltaReport** cmdlet to compare the two and get a full Delta report.

**Comment by stevemsaunders** [comment]
![MyTry1](https://user-images.githubusercontent.com/5722808/83596725-608d2780-a533-11ea-907a-fb4d1255a84a.PNG)
![MyTry4_dev](https://user-images.githubusercontent.com/5722808/83596735-671b9f00-a533-11ea-97d7-00eb9bb407d4.PNG)
![MyTry5_dev](https://user-images.githubusercontent.com/5722808/83596743-6b47bc80-a533-11ea-9869-2da5322fa6da.PNG)


Nik,Thanks for getting back to me so quickly.
Turns out the problem goers a lot deeper, into basic requirements for the cmdlet/Azure permissions
Background: Client - Vanilla Windows 10 Home Edition with anti-virus; Powershell version 5.1.18362.752; Powershell run as Administrator; Azure/O365 environment - large user base with a strong emphasis on security controls (BYOD so "web clients only" (O365 apps blocked) on PCs to do basic DLP; O365 mobile apps OK with Intune); wanted to use your project to showcase DSC capability and configuration tracking
"Normal" run using GlobalAdmin privileges - ends with an essentially "null" M365tenantConfig.ps1 file
"M365DSCDevBranch" run ended the same way, but with way more errors
[M365TenantConfig.ps1.txt](https://github.com/microsoft/Microsoft365DSC/files/4720538/M365TenantConfig.ps1.txt)

**Comment by stevemsaunders** [comment]
I'd like to provide more troubleshooting details but no entries were created within the local event viewer

**Comment by desmay** [comment]
Steve I'm getting same error on Install-M365DevBranch so we'll look into this issue. Can you try running the Install-Module Microsoft365DSC -force then run Export-M365DSCConfiguration.

**Comment by stevemsaunders** [comment]
....basic questions, being a PS configuration-as-code newbie: 
1) what additional permissions/configuration settings are required on the Azure/O365 Subscription, IN ADDITION TO Global Admin rights, in order to make this work?  
2) What log files (and/or associated dashboards ... or is this a Jupyter Notebook calling API XYZ scenario ?) within the Azure/O365 subscription would show errors/failure/completion for interactions with M365DSC? 

Feel free to tell me RTFM, as long as it's accompanied by relevant URLs ...  ;-)

**Comment by stevemsaunders** [comment]
3.  are you using Azure Powershell or Azure AD Powershell or both? If both, which is used for which elements?

**Comment by desmay** [comment]
Steve

Permissions are determined by workload so for example extracting SPO could use SP Admin instead of a GA account. We use a module called MSCloudLoginAssist which connects to all the various workloads. For Azure its using the AzureADPreview modules as they are need for AAD Group naming.

Do you have any conditional access enabled for tenant that would block connection from non-managed devices ? Are there any error files in the directory you ran the export?

**Comment by albandrod** [comment]
same error here, I tried to execute the Assert, but was impossible. I can provide more information as well to reproduce the issue. I tried in two different tenants with the same result

**Comment by desmay** [comment]
Can you try latest version https://www.powershellgallery.com/packages/Microsoft365DSC/1.20.603.1.

@albandrod  Are you able to run an export-m365dscconfiguration.

**Comment by albandrod** [comment]
yes I tried, also I updated the modules with -allowclobber and -force parameters... but not possible

**Comment by albandrod** [comment]
@desmay I solved the error starting winrm, but now, the error is a different one:

PS C:\WINDOWS\system32> Assert-M365DSCTemplate -TemplatePath "C:\Users\myuser\Downloads\SPO-M365Business-Baseline.M365"
Only the first eight characters of a custom log name are significant, and there is already another log on the system
using the first eight characters of the name given. Name given: 'Microsoft365DSC', name of existing log:
'Microsoft-ServerManagementExperience'.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : NewEventlogException,Microsoft.PowerShell.Commands.NewEventLogCommand
    + PSComputerName        : localhost

The source name "MSFT_SPOSite" does not exist on computer "localhost".
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteEventLogCommand
    + PSComputerName        : localhost

The PowerShell DSC resource '[SPOSite]DefaultRootSite' with SourceInfo
'C:\Users\myuser\AppData\Local\Temp\3b7d8863-62a6-4199-9124-e03f3a0d1bf7.ps1::55::9::SPOSite' threw one or more
non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel
called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

The environment does not match the template. The following component(s) are not in the Desired State:

**Comment by NikCharlebois** [comment]
Please run 
winrm quickconfig -force 

on the machine and retry running the command

**Comment by micromega-prog** [comment]
bingo! that worked. The error made it look like an issue on the endpoint as opposed to on the local computer that I'm running the commands from. 

I'm now seeing the same error message that someone else reported earlier:

_PowerShell DSC resource MSFT_TeamsCallingPolicy  failed to execute Test-TargetResource functionality with error
message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is
set to Stop: [admin0b.online.lync.com] Connecting to remote server admin0b.online.lync.com failed with the following
error message : The WinRM client cannot process the request. The authentication mechanism requested by the client is
not supported by the server or unencrypted traffic is disabled in the service configuration. Verify the unencrypted
traffic setting in the service configuration or specify one of the authentication mechanisms supported by the server.
To use Kerberos, specify the computer name as the remote destination. Also verify that the client computer and the
destination computer are joined to a domain. To use Basic, specify the computer name as the remote destination,
specify Basic authentication and provide user name and password. Possible authentication mechanisms reported by
server: For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost_
