### ISSUE TITLE
SPOApp Fails Without an App Catalog

### ISSUE THREAD

**Issue by NikCharlebois** [microsoft/Microsoft365DSC#95]
#### Details of the scenario you tried and the problem that is occurring
When doing a ReverseDSC Extraction of a tenant without an App Catalog Configured, the extraction will silently abort upon hitting the SPOApp resource (if selected as part of the extraction process). We need a way to gracefully print a warning to the user to let them know that no catalogs have been defined for the tenant, and then move on with the extraction.

#### Verbose logs showing the problem
Extracting ODSettings...
Extracting SPOApp...
Cancel

#### Suggested solution to the issue
Handle Error gracefully

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)
Alpha

**Comment by NikCharlebois** [comment]
In talking with @VesaJuvonen this is currently a limitation of the API where we can't programatically create a Tenant-Wide App Catalog. Will need to mitigate this for the time being.

**Comment by cwdata** [comment]
I'd say creating a tenant wide app catalog from O365DSC is not the way to go here. It should be checked if this catalog exists or not so that the modules that rely on the app catalog could be skipped automatically.
A way to achieve this is using a rest call:
```
Invoke-PnPSPRestMethod -Url '/_api/SP_TenantSettings_Current'
```
This call needs a login via Connect-PnPOnline first. It returns a key/value pair:
```
Key                 Value
---                 -----
CorporateCatalogUrl https://<tenanturl>.sharepoint.com/sites/<appcatalogname>
```
I currently don't have access to a tenant without an app catalog but maybe someone else could tell us how the result will be when there is no catalog set up.
