### ISSUE TITLE
The maximum number of concurrent shells for this user has been exceeded.

### ISSUE THREAD

**Issue by bubbletroubles** [microsoft/Microsoft365DSC#966]
#### Details of the scenario you tried and the problem that is occurring
I am running ```Start-DSCConfiguration extract -Wait -Verbose -Force``` a few times within a 5 minute window for testing. It seems the number of Teams/Skype sessions is exceeded. 

Does M365DSC clean up old sessions after each run?

#### Verbose logs showing the problem

```
Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The
WS-Management service cannot process the request. The maximum number of concurrent shells for this user has been
exceeded. Close existing shells or raise the quota for this user. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : AuthenticationError: (:) [], CimException
    + FullyQualifiedErrorId : New-CsOnlineSession,Microsoft.Open.Teams.SfbOnline.CsSession.NewCsOnlineSession
    + PSComputerName        : localhost

Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error message : The
WS-Management service cannot process the request. The maximum number of concurrent shells for this user has been
exceeded. Close existing shells or raise the quota for this user. For more information, see the
about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : ResourceUnavailable: (:) [], CimException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Open.Te
   ams.SfbOnline.CsSession.NewCsOnlineSession
    + PSComputerName        : localhost
```

#### Suggested solution to the issue
Disconnect from sessions before the script exits

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Start-DSCConfiguration extract -Wait -Verbose -Force
```

#### The operating system the target node is running

OsName               : Microsoft Windows Server 2019 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version of the DSC module that was used ('dev' if using current dev branch)
 1.20.1202.1

**Comment by NikCharlebois** [comment]
This is actually due to the way the Skype for Business Online module generates and interacts with its proxy functions. You would get the same behavior if you were to run multiple PowerShell sessions within the same 5 minutes period and try leveraging the SfBO module directly. We went back and forth on this within the team to decide whether or not the MSCloudLoginAssistant module should detect these situations and wait for a runspace to be freed. This however could result in 10 minutes wait which would end up causing more confusion than anything else. 

The best solution is to keep using the same PowerShell instance for each export.
