### ISSUE TITLE
[All SPOSite releated resources] Add possibility to export a selection of site collections

### ISSUE THREAD

**Issue by ykuijs** [microsoft/Microsoft365DSC#987]
#### Details of the scenario you tried and the problem that is occurring
When exporting site collections and all related settings, currently all site collections are exported. Would it be an idea (or even possible) to add a filter possibility so that you are able to select a subset of site collections?

#### Suggested solution to the issue
If possible, add the possibility to specify a subset of site collections to export.

#### Version of the DSC module that was used ('dev' if using current dev branch)
Dev

**Comment by NikCharlebois** [comment]
Love the idea. In the Go-Local Migration we introduced a -start and -end parameters to export in batches. However this approach doesn't provide a great way to select only specific items as it just grabs a random batch. How would you envision this working for SPOSite?

**Comment by NikCharlebois** [comment]
While the idea is great, this would open a can of worm where other resources could also benefit from this. ReverseDSC is meant to take a full snapshot of an environment. Customer who absolutely require filtering on SPOSite collections can easily fork the M365DSC solution and build their own. The fact that resources that normally take the longer are those that are in the Data plane instead of the control plane contributes to the decision not to implement this.
